Repository chrismattmann/tika-python, pull requests merged in 2019-12, with the labels that each got.

#265 added documentation for airgap setup
  README.md
Labels: enhancement, help wanted

#261 fix bug: Further bug fix #222
  tika/tika.py
Labels: bug, enhancement

#264 ResourceWarning issues. Fixes #262 and #263
  tika/tika.py
Labels: bug, enhancement

#259 expose service in the from_file parser
  tika/parser.py
  tika/tests/test_from_file_service.py
Labels: enhancement, help wanted

#269 Allow parsing from binary streams
  tika/parser.py
  tika/tests/files/rwservlet.pdf
  tika/tests/test_tika.py
  tika/tika.py
Labels: enhancement
