Repository chrismattmann/tika-python, pull requests merged in 2020-02, with the labels that each got.

#256 Add killServer() function
  README.md
  tika/tests/test_tika.py
  tika/tika.py
Labels: enhancement

#276 fix(): pyyaml dropped support for python 3.4
  requirements.txt
Labels: bug, enhancement, py2, py3

#280 Fix TikaServerProcess
  tika/tika.py
Labels: bug, enhancement
