Repository chrismattmann/tika-python, pull requests merged in 2020-03, with the labels that each got.

#281 Revised patch from commit ea4ce60
  tika/tika.py
Labels: bug, enhancement

#284 fix bug: non-ascii file name not supported in detect type
  tika/tika.py
Labels: bug, enhancement

#283 fix ocasional OSError
  tika/tika.py
Labels: bug, enhancement, help wanted

#289 Fix "_csv.Error: line contains NUL"
  .gitignore
  tika/unpack.py
Labels: bug, enhancement

#295 unpack: use with blocks when handling files
  tika/unpack.py
Labels: enhancement, help wanted

#296 Updated link
  README.md
Labels: enhancement
