Repository chrismattmann/tika-python, pull requests merged in 2022-12, with the labels that each got.

#380 Adds code highlighting to README.md
  README.md
Labels: enhancement

#316 Tika 1.24.1 - gzip (de)compression
  .travis.yml
  README.md
  setup.py
  tika/__init__.py
  tika/tests/memory_benchmark.py
  tika/tests/test_benchmark.py
  tika/tests/test_tika.py
  tika/tests/utils.py
  tika/tika.py
Labels: enhancement

#366 Fix unnecessary retries after successful startup
  tika/tika.py
Labels: bug, enhancement

#354 [documentation] Add example with byte buffer
  README.md
Labels: enhancement, help wanted

#364 Allow for headers in unpack.from_file
  tika/unpack.py
Labels: enhancement
